[tool.poetry]
name = "scrapyu"
version = "0.1.1"
description = "Scrapy utils"
authors = [
    "lin-zone <z_one10@163.com>",
]
license = "MIT license"
readme = "README.md"
repository = "https://github.com/lin-zone/scrapyu"
keywords = ["scrapy", "pipelines", "middlewares", "utils"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"